### ISSUE TITLE
ingress の api の修正

### ISSUE THREAD

**Issue by iganari** [iganari/handson-gke#13]
https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#all-supported-versions_1

**Comment by iganari** [comment]
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: "frontendconfig"
...
```
